# -*- mode: ruby -*-
# vi: set ft=ruby :

$script = <<SCRIPT

echo "Installing dependencies ..."
sudo apt-get update
sudo apt-get install -y unzip curl jq dnsutils

echo "Determining OpenGyoza version to install ..."
if [ -z "$GYOZA_DEMO_VERSION" ] && [ -n "$CONSUL_DEMO_VERSION" ]; then
    GYOZA_DEMO_VERSION="$CONSUL_DEMO_VERSION"
fi
if [ -z "$GYOZA_DEMO_VERSION" ]; then
    GYOZA_DEMO_VERSION=$(curl -s https://api.github.com/repos/opengyoza/opengyoza/releases/latest | jq -r .tag_name | sed 's/^v//')
fi

echo "Fetching OpenGyoza version ${GYOZA_DEMO_VERSION} ..."
cd /tmp/
curl -s -L https://github.com/opengyoza/opengyoza/releases/download/v${GYOZA_DEMO_VERSION}/gyoza_${GYOZA_DEMO_VERSION}_linux_amd64.zip -o gyoza.zip

echo "Installing OpenGyoza version ${GYOZA_DEMO_VERSION} ..."
unzip gyoza.zip
sudo chmod +x gyoza consul
sudo mv gyoza /usr/bin/gyoza
sudo mv consul /usr/bin/consul

sudo mkdir /etc/consul.d
sudo chmod a+w /etc/consul.d

SCRIPT

# Specify an OpenGyoza version
CONSUL_DEMO_VERSION = ENV['CONSUL_DEMO_VERSION']
GYOZA_DEMO_VERSION = ENV['GYOZA_DEMO_VERSION'] || CONSUL_DEMO_VERSION

# Specify a custom Vagrant box for the demo
DEMO_BOX_NAME = ENV['DEMO_BOX_NAME'] || "debian/stretch64"

# Vagrantfile API/syntax version.
# NB: Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = DEMO_BOX_NAME

  config.vm.provision "shell",
                          inline: $script,
                          env: {
                            'CONSUL_DEMO_VERSION' => CONSUL_DEMO_VERSION,
                            'GYOZA_DEMO_VERSION' => GYOZA_DEMO_VERSION
                          }

  config.vm.define "n1" do |n1|
      n1.vm.hostname = "n1"
      n1.vm.network "private_network", ip: "172.20.20.10"
  end

  config.vm.define "n2" do |n2|
      n2.vm.hostname = "n2"
      n2.vm.network "private_network", ip: "172.20.20.11"
  end
end
